os:
  - linux
  - osx

addons:
  apt_packages:
    - libgmp-dev
    - texinfo

language: c

compiler:
  - gcc
  - clang

script:
  - ./build.sh
  - git clone https://www.github.com/gap-system/gap --depth=1
  - cd gap && ./autogen.sh && ./configure --enable-hpcgap --with-ward=.. && make -j2
  - ./gap -l . tst/testinstall.g
