os:
  - linux
  - osx
env:
  - TEST_SUITE=testinstall
  - TEST_SUITE=testtravis
  - TEST_SUITE=testbugfix
language: c
compiler:
  - gcc
  - clang
branches:
  only:
    - master
# Change this to your needs
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgmp3-dev
script:
  - git clone --depth=1 https://github.com/gap-system/ward 
    cd ward
  - ./build.sh
